"""Change user

Revision ID: 8772b3e60b05
Revises: 
Create Date: 2024-01-27 12:54:39.201912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8772b3e60b05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('user_firebase_uuid_key', type_='unique')
        batch_op.create_unique_constraint(None, ['firebase_uid'])
        batch_op.drop_column('firebase_uuid')
        batch_op.drop_column('bio')
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('firebase_uuid', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_firebase_uuid_key', ['firebase_uuid'])
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
